config/routes.rb
Rails.application.routes.draw do

  resources :suggestions

  get '/suggstr', to:'wrapper#landing', as: 'landing'
  get '/goodbye', to:'wrapper#goodbye', as: 'goodbye'
  get '/learnmore', to:'wrapper#credit', as: 'credit'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/dashboard', to: 'users#dashboard', as: 'dashboard'
  get '/dashboard/:sub', to: 'users#sub_list', as: 'sub_list'

  root 'wrapper#landing'
  resources :types
  resources :medium_tags
  resources :tags
  resources :queued_media
  resources :users
  resources :media

  post 'user/:user_id/:medium_id/up', to: 'users#move_up', as: 'move_medium_up'
  post 'user/:user_id/:medium_id/down', to: 'users#move_down', as: 'move_medium_down'
  post 'user/:user_id/:medium_id/completed', to: 'users#completed', as: 'medium_completed'
  post 'user/:user_id/:medium_id/rated', to: 'users#rated', as: 'medium_rated'
  get 'user/:user_id/history', to: 'users#history', as: 'user_history'
  get 'users/:id/suggestions', to: 'users#suggestions', as: 'user_suggestions'
  get 'media/:id/suggest', to: 'suggestions#new', as: 'medium_suggestion'
  post 'media/:id/suggest', to: 'suggestions#create'
  post 'queued_media', to: 'queued_media#create'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :queued_media
  has_many :media, through: :queued_media
  has_many :rating_records
  has_many :sent_suggestions, class_name: "Suggestion", foreign_key: "sender_id"
  has_many :received_suggestions, class_name: "Suggestion", foreign_key: "receiver_id"



  validates :name, presence: true
  validates :username, uniqueness: { case_sensitive: false }, presence: {message: "must be added"}
  # validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
  #   message: "must be valid address" }
  # validates :email, uniqueness: { case_sensitive: false, message: "can't be added, please try again" }
  has_secure_password

  #somehow Type.all does not work in the sub function for activerecord, how weird. Now manually writing this
  @@types = ["Book", "TV Show", "Movie", "Video Game", "Podcast"]

  #select top 5 if top list, otherwise select list of the category
  def sub_list(category)
    if category == "Top List"
      sub_list = self.top_list.sort_by {|m| QueuedMedium.find_by(medium_id: m.id, user_id: self.id).updated_at}.reverse
    else
      sub_category = category.sub("-", " ")[0..category.size-2]
      sub_list = category_list(sub_category)
    end
    return sub_list.flatten
  end

  def top_list
    top_x = 5
    top_list = []
    @@types.each do |type|
      if category_list(type).size >= top_x
        top_list << category_list(type)[0..top_x-1]
      else
        top_list << category_list(type)
      end
    end
    return top_list.flatten
  end

  def category_list(category)
    full_list = self.sorted_queued_list
    return full_list.select{|m| m.type.name == category}
  end

  def sorted_queued_list
    self.reload
    sorted_queued_list = []
    queue_list = self.queued_media.select{|m| m.completed != true}.sort_by {|m| 0-m.priority_score}
    queue_list.each do |ql|
      sorted_queued_list << Medium.find(ql.medium_id)
    end
    return sorted_queued_list
  end

  def move_medium_up(medium_up)
    category = "#{medium_up.type.name.sub(" ", "-")}s"
    queued_list = self.sub_list(category)
    current_spot = queued_list.index(medium_up)

    #ensure the top of the list cannot be moved even further
    if current_spot != 0
      medium_down = queued_list[current_spot-1]
      old_queued_medium = QueuedMedium.find_by(user_id:self.id, medium_id:medium_up.id)
      new_queued_medium = QueuedMedium.find_by(user_id:self.id, medium_id:medium_down.id)
      # swap with neighbor
      old_priority_score = old_queued_medium.priority_score
      old_queued_medium.update(priority_score: new_queued_medium.priority_score)
      new_queued_medium.update(priority_score: old_priority_score)
    end
  end


  def move_medium_down(medium_down)
    category = "#{medium_down.type.name.sub(" ", "-")}s"
    queued_list = self.sub_list(category)
    current_spot = queued_list.index(medium_down)
    if current_spot != queued_list.size-1
      medium_up = queued_list[current_spot+1]
      old_queued_medium = QueuedMedium.find_by(user_id:self.id, medium_id:medium_down.id)
      new_queued_medium = QueuedMedium.find_by(user_id:self.id, medium_id:medium_up.id)
      old_priority_score = old_queued_medium.priority_score
      old_queued_medium.update(priority_score: new_queued_medium.priority_score)
      new_queued_medium.update(priority_score: old_priority_score)
    end
  end

  def completed_queued_list
    self.reload
    completed_queued_list = []
    queue_list = self.queued_media.select{|m| m.completed == true}
    queue_list.each do |ql|
      completed_queued_list << Medium.find(ql.medium_id)
    end
    return completed_queued_list
  end

  def sort_by_time(unsorted_list)
    return unsorted_list.sort_by{|m| m.updated_at}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_current_user, only: [:move_up, :move_down, :completed, :rated, :history, :dashboard, :sub_list, :suggestions]
   before_action :require_login, only: [:dashboard, :move_up, :move_down, :completed, :rated, :history, :sub_list, :suggestions]

  def index
    @users = User.all
  end


  def new
      @user = User.new
  end

  def create
      @user = User.create(user_params)
      if @user.valid?
        log_in @user
          redirect_to dashboard_path
      else
         
          flash[:danger] = @user.errors.full_messages

          redirect_to new_user_path
      end
  end

  def dashboard
    if logged_in?
      if params[:q] && params[:q] != ""
        @searched = Tag.find_by(name: params[:q].downcase)
        @media = current_user.media.select{|m| m.tags.include?(@searched)}
      else
        @media = @user.sub_list("Top List")
        @sub = "Top List"
      end
    else
      redirect_to login_path
    end
  end

  def sub_list
    if logged_in?
      @media = @user.sub_list(params[:sub])
      @sub = params[:sub]
      render 'dashboard'
    else
      redirect_to login_path
    end
  end

  def move_up
    @medium = Medium.find(params[:medium_id])
    category = @medium.type.name
    @user.move_medium_up(@medium)
    url = "/dashboard/#{category.sub(" ", "-")}s"
    redirect_to url
  end

  def move_down
    @medium = Medium.find(params[:medium_id])
    category = @medium.type.name
    @user.move_medium_down(@medium)
    url = "/dashboard/#{category.sub(" ", "-")}s"
    redirect_to url
  end

  def completed
    @queued_medium = QueuedMedium.find_by(medium_id: params[:medium_id], user_id: params[:user_id])
    @queued_medium.update(completed:true)
    @medium = Medium.find(params[:medium_id])
  end

  def rated
    RatingRecord.create(user_id: params[:user_id], medium_id: params[:medium_id], rated_score: params[:category])
    redirect_to user_history_path
  end

  def history
    authorized_for((params[:user_id]))
    @media = @user.sorted_queued_list
    @completed_media = @user.completed_queued_list

  end

  def suggestions
    authorized_for((params[:id]))
    @user = User.find(params[:id])
  end


  def show
    @user = User.find(params[:id])
    @media = @user.sorted_queued_list
  end


  private

  def user_params
      params.require(:user).permit(

          :name,
          :username,
          :password
      )
  end

  def find_current_user
      @user = current_user
  end

    def require_login
      authorized?
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/completed.html.erb
<header class="masthead text-center text-white">
  <div class="masthead-content">
		<div class=container style="width:40%; height:350px; vertical-align:top; margin-left:auto; margin-right:auto" >
			<h2>What do you think of the <%=@medium.title%>?</h2>
			<br><br>
<%= form_tag "/user/#{@queued_medium.user_id}/#{@queued_medium.medium_id}/rated", method:'post' do %>
	<% RatingRecord.categories.each do |category| %>
			<label class="btn btn-dark">
				<input type="radio" name="category" autocomplete="off" value="<%= category %>"><%="     #{category}"%>
  		</label>
	<% end %>
	<br><br><br>
	<button class="btn btn-outline-light my-2 my-sm-0" type="submit">Done rating</button>
<% end %>
</div>
</div>
</header>

app/views/users/dashboard.html.erb
<div class="shadow p-3 mb-5 bg-white rounded">
  <nav class="navbar navbar-expand-lg navbar-normal">
      <%= link_to "Top List  |", dashboard_path, method:'get', class: 'navbar-brand' %>
      <%= link_to "Movies", '/dashboard/Movies', method:'get', class: 'navbar-brand' %>
      <%= link_to "TV Shows",'/dashboard/TV-Shows', method:'get', class: 'navbar-brand' %>
      <%= link_to "Books", '/dashboard/Books', method:'get', class: 'navbar-brand' %>
      <%= link_to "Video Games", '/dashboard/Video-Games', method:'get', class: 'navbar-brand' %>
      <%= link_to "Podcasts  |", '/dashboard/Podcasts', method:'get', class: 'navbar-brand' %>
      <%= link_to "Add new+", new_medium_path, method:'get', class: 'navbar-brand' %>

      <%= form_tag(dashboard_path, method: "get") do %>
      <%= text_field_tag :q, nil ,class: 'navbar-brand', placeholder: 'filter by tag...', style:"color:#4c4c4c" %>
      <%= submit_tag "Go", class: 'btn btn-sm' %>
      <% end %>
  </nav>
  <div class="small container">
    <% if @media == nil || @media == [] %>
      <br><br><br><br>
      <h2 class="text-center">Oh well.. </h2>
      <h2 class="text-center">Nothing to see here</h2>
      <br>
      <div class="text-center"><a href=<%=new_medium_path%> class="btn btn-dark btn-lg" role="button">Add to your queue</a></div>
      <br><br><br><br><br><br>
    <% else %>


    <table class="table">
      <thead>
        <tr>
          <th scope="col">Media</th>
          <th scope="col">Type</th>
          <th scope="col">Avg Rating</th>
          <th scope="col">Added</th>
          <th scope="col"> </th>
          <th scope="col"> </th>
          <th scope="col"> </th>
          <th scope="col"> </th>
          <th scope="col"> </th>
        </tr>
      </thead>
      <tbody>
        <%medium_tpye = @media.first.type.name%>
        <% @media.each do |medium| %>
        <tr>
          <%queued_medium = QueuedMedium.find_by(medium_id: medium.id, user_id: @user.id)%>
          <%queued_medium_id = queued_medium.id%>
          <td><%=link_to(medium.title, medium,html_options = {:style=>'color:#000000;'})%></td>
          <td><%=medium.type.name%></td>
          <td>
            <% if !medium.good_score %>
              <%="-"%>
            <% else %>
              <%(medium.avg_score*100/20).to_i.times do%>
                <p style="display:inline">★</p>
              <%end%>
            <% end %>
          </td>
          <td><%=time_ago_in_words(queued_medium.created_at)%> ago</td>
          <% if @sub != "Top List" && @sub != nil%>
            <td class="text-center">
              <%= link_to "<i class=\"fas fa-arrow-up\"></i>".html_safe, "/user/#{@user.id}/#{medium.id}/up", method: 'post', class:'btn btn-light btn-sm' %>
            </td>
            <td class="text-center">
              <%= link_to "<i class=\"fas fa-arrow-down\"></i>".html_safe, "/user/#{@user.id}/#{medium.id}/down", method: 'post', class:'btn btn-light btn-sm' %>
            </td>
          <% end %>
          <td class="text-center">
            <%= button_to 'Completed', "/user/#{@user.id}/#{medium.id}/completed", method: 'post', class:'btn btn-dark btn-sm form-inline' %>
          </td>
          <td class="text-center">
            <%= button_to '+', "/media/#{medium.id}/suggest", method: 'get', class:'btn btn-success btn-sm form-inline' %>
          </td>
          <%queued_medium_id = QueuedMedium.find_by(medium_id: medium.id, user_id: @user.id).id%>
          <td class="text-center">
            <%= link_to "<i class=\"fas fa-trash-alt\"></i>".html_safe, "/queued_media/#{queued_medium_id}", method: 'delete', class:'btn btn-light btn-sm' %>
          </td>
        </tr>
        <% end %>
      </tbody>
      </table>
  <% end %>
  </div>
</div>

app/views/users/history.html.erb
<div class="container">

    <% if flash[:error] %>
      <div class="notice"><font color="red">
        <ul>
            <li>
              <%= flash[:error] %>
            </li>
          <% end %>
        </ul>
        </font>
      </div>

    <% if @completed_media.length > 0 %>
    <h3>What you have completed so far </h3>
    <br>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Item</th>
          <th scope="col">Type</th>
          <th scope="col">Your rating</th>
          <th scope="col"> </th>
          <th scope="col">Time</th>
          <th scope="col"> </th>
        </tr>
      </thead>
      <tbody>

        <%n = 1%>
        <% @completed_media.each do |medium| %>
        <tr>
          <th scope="row"><%=n%></th>
          <td><%=link_to(medium.title, medium,html_options = {:style=>'color:#000000;'})%></td>
          <td><%= medium.type.name %></td>

          <%@rating_record = RatingRecord.find_by(user_id: @user.id, medium_id: medium.id)%>
          <td><%=@rating_record.rated_score%></td>

          <%if @rating_record.rated_score == "Good"%>
              <td>👏🍿</td>
          <%elsif @rating_record.rated_score == "Average"%>
              <td> </td>
          <%else%>
              <td> </td>
          <%end%>

          <td><%=time_ago_in_words(@rating_record.updated_at)%> ago</td>
          <td class="text-center"><a href=<%=medium_suggestion_path(medium)%> class="btn btn-success btn-sm" role="button">Suggest to friend</a></td>
        </tr>
        <%n += 1%>
        <% end %>
    <% else %>
        <br><br><br><br>
        <h1 class="text-center">Oh well.. </h1>
        <h1 class="text-center">You haven't completed anything yet</h1>
        <br>
        <div class="text-center"><a href=<%=media_path%> class="btn btn-primary btn-lg" role="button">Check out our amazing suggstr-base</a></div>
        <br><br><br><br><br><br><br><br><br><br><br>
    <% end %>
  </tbody>

</table>
</div>

app/views/users/index.html.erb

<h3>User</h3>

<ul>
  <% @users.each do |user| %>
        <li>
          <%=link_to user.name, user %>
        </li>
      <br>
  <% end %>
</ul>

app/views/users/new.html.erb
<%if logged_in? %>
<h1>Hi <%= current_user.name %>!</h1>




<%= button_to "Back to dashboard", dashboard_path, method: :get%>
<% else %>

  <br>

<div style= "max-width: 450px; max-height: 500px;margin: auto;" class="shadow p-3 mb-5 bg-white rounded">
  <nav style="display: flex; flex-direction: column;" class="navbar navbar-expand-lg navbar-normal">
      <h3 class="form-header">Sign up to Suggstr</h3>
        <h5 class="form-header">And start suggstng!</h5>

  </nav>
<%= form_for @user, html: {class: "text-center", style: "margin-top: 1rem;" } do |f| %>
    <%= f.text_field :name, placeholder: "name", class: "input-form" %><br>
    <%= f.text_field :username, placeholder: "username", class: "input-form"  %><br>
    <%= f.password_field :password, placeholder: "password", class: "input-form"  %><br>

    <%= f.submit "Sign up", class: "btn btn-primary btn-m rounded-pill mt-2"  %>
<% end %>
<p class = "text-center" style = "margin-top: 2rem;" >Already have an account? <br>
<%= link_to "Click here to login", login_path %>
</p>

<% end %>

 <% if flash.now[:danger] %>
      <div><font color="red">
      <ul>
        <% flash.now[:danger].each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
      </font>
    </div>
    <% end %>

</div>

app/views/users/show.html.erb
<h2><%=@user.name%></h2>

<% if @media.length == 0 %>


<h3>This users queue is empty.</h3>

<% else %>

<% if current_user == @user %>
<%= button_to  "Go to your dashboard", dashboard_path, method: :get , class:'btn btn-primary' %>
<% end %>

<h3><%=@user.name%>'s current queue is:</h3>

<table>
  <tr>
    <th>Medium</th>
    <th>Type</th>
    <th> </th>
    <th> </th>
    <th> </th>
    <th> </th>
  </tr>

<% @media.each do |medium| %>
<tr>
<th><%=link_to medium.title, medium%></th>
<th><%=medium.type.name%></th>

<%queued_medium_id = QueuedMedium.find_by(medium_id: medium.id, user_id: @user.id).id%>

</tr>
<% end %>
</table>

<br><br>

<% end %>

app/views/users/suggestions.html.erb
<div class="shadow p-3 mb-5 bg-white rounded" style="width:95%; height:250; vertical-align:top; margin-right:auto; margin-left:auto" >

<h2>Your Suggestions</h2>



<% if @user.received_suggestions.length == 0  %>
<h4>You have no new suggestions </h4>


<%= button_to "browse media", media_path, method: :get, class:'btn' %>

<% else %>

<table class="table" >
  <tbody>

    <% @user.received_suggestions.each do |sug| %>
      <tr>
        <td> <%= link_to "#{sug.medium.title} (#{sug.medium.type.name}) was suggested by #{sug.sender_object.name} #{time_ago_in_words(sug.created_at)} ago.", sug %> </td>
        <td> <%= link_to "<i class=\"fas fa-trash-alt\"></i>".html_safe, sug, method: 'delete', class:'btn btn-dark btn-sm ', style:"width:30px" %> </td>
      </tr>
    <% end %>

  </tbody>
</table>

<% end %>


</div>