config/routes.rb
Rails.application.routes.draw do

  resources :suggestions

  get '/suggstr', to:'wrapper#landing', as: 'landing'
  get '/goodbye', to:'wrapper#goodbye', as: 'goodbye'
  get '/learnmore', to:'wrapper#credit', as: 'credit'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/dashboard', to: 'users#dashboard', as: 'dashboard'
  get '/dashboard/:sub', to: 'users#sub_list', as: 'sub_list'

  root 'wrapper#landing'
  resources :types
  resources :medium_tags
  resources :tags
  resources :queued_media
  resources :users
  resources :media

  post 'user/:user_id/:medium_id/up', to: 'users#move_up', as: 'move_medium_up'
  post 'user/:user_id/:medium_id/down', to: 'users#move_down', as: 'move_medium_down'
  post 'user/:user_id/:medium_id/completed', to: 'users#completed', as: 'medium_completed'
  post 'user/:user_id/:medium_id/rated', to: 'users#rated', as: 'medium_rated'
  get 'user/:user_id/history', to: 'users#history', as: 'user_history'
  get 'users/:id/suggestions', to: 'users#suggestions', as: 'user_suggestions'
  get 'media/:id/suggest', to: 'suggestions#new', as: 'medium_suggestion'
  post 'media/:id/suggest', to: 'suggestions#create'
  post 'queued_media', to: 'queued_media#create'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <%= favicon_link_tag 'favicon.ico' %>

  <title>Suggstr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Bootstrap core CSS -->

  <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Keeping the custom fonts -->
  <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">


</head>
<body>


<!-- Navigation -->
<!-- Navigation for logged in userss-->
<% if logged_in? %>
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
<div class="container">

  <%= link_to "My List", dashboard_path, method:'get', class: 'navbar-brand' %>
  <%= link_to "My Suggestions(#{current_user.received_suggestions.length})", user_suggestions_path(current_user), method:'get', class: 'navbar-brand' %>
  <%= link_to "History", user_history_path(current_user), method:'get', class: 'navbar-brand' %>
  <%= link_to "Browse", media_path, method:'get', class: 'navbar-brand' %>

  <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to "Log Out, #{current_user.name} ", logout_path, method:'delete', class: 'nav-link' %>
      </li>
    </ul>
  </div>
</div>
</nav>

<% else %>
<!-- Navigation for none logged in userss-->
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
<div class="container">
  <a class="navbar-brand" href="/">Explore Suggstr</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="<%=signup_path%>">Sign Up</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=login_path%>">Log In</a>
      </li>
    </ul>
  </div>
</div>
</nav>
<% end %>


<% if request.fullpath == '/' || request.fullpath.include?("completed") %>
  <%= yield %>
<% else %>
  <div class="main container">
      <% if flash.now[:message] %>
        <div class="notice"><font color="green">
          <ul>
              <li>

                <%= flash.now[:message] %>
              </li>
          </ul>
          </font>
        </div>
      <% end %>
    <% if flash.now[:errors] %>
      <div><font color="red">
      <ul>
        <% flash.now[:errors].each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
      </font>
    </div>
    <% end %>
  <%= yield %>
  <br><br>
  </div>
<% end %>




<!-- Footer -->
<footer class="py-3 bg-black">
<div class="container">
<p class="m-0 text-center text-white small">Copyright &copy; SuggstrGang 2019</p>
<p class="m-0 text-center text-white small">Powered by Ruby on Rails on Bootstrap</p>
<p style="color: white;"  class= "m-0 text-center text-white small"><%= link_to "Meet the team", '/learnmore'%></p>
</div>
<!-- /.container -->
</footer>
</body>
</html>